koryo_fes_system/account/urls.py
from django.conf.urls import url
from django.urls import path
from django.views.generic import RedirectView

from . import views


app_name="account"
urlpatterns = [
    path('', RedirectView.as_view(url='/login/')),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
]

koryo_fes_system/koryo_fes_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
# from django.contrib.auth.models import Group


admin.site.site_title = '蛟龍祭入場管理システム Marronnier'
admin.site.site_header = '蛟龍祭入場管理システム Marronnier'
admin.site.index_title = 'メニュー'
# admin.site.unregister(Group)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('room_access_system.urls')),
    path('api/', include("number_of_people_api.urls")),
    # path('', RedirectView.as_view(url='/home/')),
    path('', include('account.urls')),
]

koryo_fes_system/number_of_people_api/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('copy_check/<slug:user_num>', views.CopyCheckDataApi.as_view(), name='api'),
]

koryo_fes_system/room_access_system/urls.py
from django.urls import path
from . import views


app_name="room_access_system"
urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('room_access/<slug:room_name>/<slug:enter_or_leave>', views.RoomAccessView.as_view(), name="room_access"),
    path('ajax_post', views.ajax_response, name='ajax_post'),
    path('congestion_level_page', views.CongestionLevelView.as_view(), name='congestion_level'),
]

koryo_fes_system/account/models.py
from django.db import models

# Create your models here.

koryo_fes_system/number_of_people_api/models.py
from django.db import models

# Create your models here.

koryo_fes_system/room_access_system/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class RoomAccessData(models.Model):
    room_name = models.CharField(
        max_length=50,
        blank=False,
        null=False,
    )
        
    user_num = models.IntegerField(
        default=0,
        blank=False,
        null=False,
    )

    entered_or_left = models.IntegerField(
        default=0,
        blank=False,
        null=False,
    )

    entered_or_left_time = models.DateTimeField(
        default=timezone.now,
        blank=False,
        null=False,
    )


class NumberOfPeopleData(models.Model):
    room_name = models.CharField(
        max_length=50,
        blank=False,
        null=False,
    )
    
    number_of_people = models.BigIntegerField(
        default=0,
        blank=False,
        null=False,
    )

koryo_fes_system/account/forms.py
from django.contrib.auth.forms import AuthenticationForm

# ログインフォーム
class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"

koryo_fes_system/room_access_system/forms.py
from dataclasses import field
from django import forms

from .models import RoomAccessData

class PostForm(forms.ModelForm):
    class Meta:
        model = RoomAccessData
        fields = ('room_name', 'user_num', 'entered_or_left')

koryo_fes_system/account/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

from . import forms


class TopPageView(TemplateView):
    template_name = "account/top.html"

# ログインページ
class LiginView(LoginView):
    form_class = forms.LoginForm
    template_name = "registration/login.html"

# ログアウトページ
class LogoutView(LoginRequiredMixin, LogoutView):
    template_name = "registration/login.html"

koryo_fes_system/number_of_people_api/views.py
from django.shortcuts import render
from django.views import View
from django.http import JsonResponse, HttpResponse
from django.db.models import Sum
import json

from room_access_system.models import RoomAccessData

# Create your views here.
class NumberOfPeopleApiView(View):
    def get(self, request):
        room_access_data = RoomAccessData.objects

        saved_room_name_list = room_access_data.values_list('room_name', flat=True) # データベースからroom_nameのカラムのデータを全部取得
        room_name_list = list(set(saved_room_name_list)) # 上で取得したリストの重複を削除
        
        number_of_people_dict = {}

        for room_name in room_name_list:
            room_data = room_access_data.filter(room_name=room_name).all()
            number_of_people = room_data.aggregate(Sum('entered_or_left')).get('entered_or_left__sum')

            number_of_people_dict.setdefault(room_name, number_of_people)


        json_data = json.dumps(number_of_people_dict)

        return HttpResponse(json_data, content_type="application/json")

class CopyCheckDataApi(View):
    def get(self, request, user_num):
        user_num = int(user_num)

        copy_check_num = RoomAccessData.objects.filter(room_name='koryo-fes', user_num=user_num).all().aggregate(Sum('entered_or_left')).get('entered_or_left__sum')

        json_data = json.dumps({"copy_check_num": copy_check_num})

        return HttpResponse(json_data, content_type="application/json")

koryo_fes_system/room_access_system/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import FormView, TemplateView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
import json

from .forms import PostForm
from .models import RoomAccessData, NumberOfPeopleData

# Create your views here.
class HomeView(LoginRequiredMixin, TemplateView):
    template_name = 'room_access_system/home.html'


"""
# このviewは今は使っていないですが、一応残しておきます。by野村
class PostFormView(FormView):
    # 最初にurlでアクセスしたときの処理
    def get(self, request, room_name, enter_or_leave):
        if enter_or_leave == 'enter':
            parameter = 1
        elif enter_or_leave == 'leave':
            parameter = -1

        form = PostForm(request.GET or None, initial={'room_name': room_name, 'entered_or_left': parameter})

        return render(request, 'room_access_system/room_access.html', dict(form=form))

    form_class = PostForm

    
    def get_success_url(self, **kwargs):
        return reverse_lazy('room_access', kwargs={'room_name': self.kwargs['room_name'], 'enter_or_leave': self.kwargs['enter_or_leave']})

    # postされたデータの処理
    def form_valid(self, form):
        room_name = form.cleaned_data['room_name']
        user_num = form.cleaned_data['user_num']
        entered_or_left = form.cleaned_data['entered_or_left']

        RoomAccessData.objects.create(
            room_name = room_name,
            user_num = user_num,
            entered_or_left = entered_or_left,
        )

        return super().form_valid(form)
"""


# ajaxの処理
@login_required
def ajax_response(request):
    if request.method == 'POST':

        room_name = request.POST.get('room_name')
        user_num = int(request.POST.get('user_num'))
        entered_or_left = request.POST.get('entered_or_left')


        RoomAccessData.objects.create(
            room_name = room_name,
            user_num = user_num,
            entered_or_left = entered_or_left,
        )
        
                    
        return HttpResponse("こんにちは")


class RoomAccessView(LoginRequiredMixin, View):
    def get(self, request, room_name, enter_or_leave):
        if enter_or_leave == 'enter':
            parameter = 1
        elif enter_or_leave == 'leave':
            parameter = -1

        form = PostForm(request.GET or None, initial={'room_name': room_name, 'entered_or_left': parameter})

        return render(request, 'room_access_system/room_access.html', dict(form=form))


class CongestionLevelView(TemplateView):

    template_name = 'room_access_system/congestion_level.html'

    def get_context_data(self, **kwargs):

        number_of_people_data = NumberOfPeopleData.objects.all()

        context = super().get_context_data(**kwargs)
        context['data'] = number_of_people_data

        return context

    # def get(self, request):

    #     context = {
    #         'data': number_of_people_data,
    #     }

    #     return render(request, 'room_access_system/congestion_level.html', context)

koryo_fes_system/templates/room_access_system/1-1enter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>1-1enter</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-sm-7 col-md-6 mx-auto">
                    {{ form.room_name }}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-7 col-md-6 mx-auto">
                    {{ form.user_num }}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-7 col-md-6 mx-auto">
                    {{ form.entered_or_left }}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-7 col-md-6 mx-auto text-center">
                    <button type="submit" class="btn bg-white shadow">送信</button>
				</div>
            </div>
        </form>
    </div>
</body>
</html>

koryo_fes_system/templates/room_access_system/enter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>1-1enter</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-sm-7 col-md-6 mx-auto">
                    {{ form.room_name }}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-7 col-md-6 mx-auto">
                    {{ form.user_num }}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-7 col-md-6 mx-auto">
                    {{ form.entered_or_left }}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-7 col-md-6 mx-auto text-center">
                    <button type="submit" class="btn bg-white shadow">送信</button>
				</div>
            </div>
        </form>
    </div>
</body>
</html>

koryo_fes_system/templates/room_access_system/room_access.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>入場管理システム</title>
    <link rel="stylesheet" href="{% static 'room_access_system/css/room_access_style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="{% static 'room_access_system/js/jsQR.js' %}"></script>
</head>

<body style="max-width: 640px;margin: 0 auto;">
    <div id='page-name-container'>
        <h1 id="page-name"></h1>
    </div>
    <div id="output">
      <h1 id="outputMessage"></h1>
    </div>
    <canvas id="canvas" style="width:100%"></canvas>

    <div class="container mt-4">
        <form action="" method="POST" id="post-form">
            <div class="row w-25">
                {% csrf_token %}
                {{ form.room_name.as_hidden }}
                {{ form.entered_or_left.as_hidden }}
                {{ form.user_num }}
				<button type="submit" class="btn btn-primary mt-4">送信</button>
            </div>
        </form>
        <label><input id="camera-checkbox" type="checkbox" onclick="cameraChange()">カメラを切り替える</label>
    </div>

    <p>このページの音声はOtoLogicの音声を使用しています。</p>
    <script>
        "use strict";
        // システムのユーザーがページから離れようとしたときの処理
        window.onbeforeunload = function(e) {
            return "ブラウザを閉じても良いでしょうか？";
        }

        // ajaxの処理
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
      
        var csrftoken = getCookie('csrftoken');
      
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
      
        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

		function send() {
            const entranceMusic = new Audio("{% static 'room_access_system/sound/entrance.mp3' %}");
            const errorMusic = new Audio("{% static 'room_access_system/sound/error.mp3' %}");

            var user_num_value = $('#id_user_num').val();
			var room_name_value = $('#id_room_name').val();
            var entered_or_left_value = $('#id_entered_or_left').val();

            console.log(user_num_value);

            $.ajax({
                'url': "{% url 'room_access_system:ajax_post' %}",
                'type': 'POST',
                'data': {
                    'room_name': room_name_value,
                    'user_num': user_num_value,
                    'entered_or_left': entered_or_left_value,
                },
                'dataType': 'json',
            }).done(function(response){
                var response = response;
                console.log(response);
            });

            $('#id_user_num').val(0);
		}


        // 入場する部とチケットがあっているかの確認、チケットの偽装の確認
        function validation() {
            const entranceMusic = new Audio("{% static 'room_access_system/sound/entrance.mp3' %}");
            const errorMusic = new Audio("{% static 'room_access_system/sound/error.mp3' %}");


            const dateData = new Date();
            const date = dateData.getDate();
            const time = dateData.getHours();

            console.log(date);
            console.log(time);     
            
            let termCheckNum;

            // 入場する部とチケットがあっているかの確認
            if (date === 3 && time < 13) {
                termCheckNum = 1;
            }
            else if (date === 4 && time >= 13) {
                termCheckNum = 2;
            }
            else if (date === 5 && time < 13) {
                termCheckNum = 3;
            }
            else if (date === 5 && time >= 13) {
                termCheckNum = 4;
            }

            console.log(termCheckNum);


            var user_num_value = $('#id_user_num').val();

            console.log(user_num_value);

            const numList = String(user_num_value).split(''); // 各桁の数値を取り出したリストを作成

            console.log(numList);

            const termNum = Number(numList[1]);

            const a = Number(numList[2]);
            const b = Number(numList[3]);
            const c = Number(numList[4]);
            const d = Number(numList[5]);

            const x = Number(numList[6]);

            const checkNum = (a*1 + b*3 + c*1 + d*3) % 10;

            if (checkNum === x && termCheckNum === termNum) {
                console.log('正規のチケットです。');
                entranceMusic.play();
                send();
            }

            else if (user_num_value === null || user_num_value === '') {
                $('#id_user_num').val(0);
            }

            else {
                console.log('偽装の疑いあり。');
                errorMusic.play();
            }
        }


        $('#post-form').on('submit', function(e) {
			e.preventDefault();
            
            validation();
		});

        // どのページになのかの表示
        var room_name_value = $('#id_room_name').val();
        var entered_or_left_value = $('#id_entered_or_left').val();

        switch (room_name_value) {
            case 'koryo-fes':
                room_name_value = '会場全体入口(正門)';
                break;
            case 'obara':
                room_name_value = '小原玲さん写真展';
                break;
            case 'kuizukenkyuu':
                room_name_value = 'クイズ研究同好会';
                break;
            case 'chireki-syashin-bungei':
                room_name_value = '地歴部、写真部、文芸部';
                break;
            case 'bijutsu-shodou':
                room_name_value = '美術部、書道部';
                break;
            case 'tetsudou':
                room_name_value = '鉄道研究部';
                break;
            case 'science':
                room_name_value = '科学・物理部';
                break;
            case 'koryo-3f':
                room_name_value = '将棋部、茶道部、囲碁部、百人一首部';
                break;
            case 'kyudou':
                room_name_value = '弓道部';
                break;
            case 'taiikukan':
                room_name_value = '体育館';
                break;
            case 'kinenkan':
                room_name_value = '記念館';
                break;
            case 'live':
                room_name_value = 'ライブ会場';
                break;
            case 'rest-area':
                room_name_value = '休憩所'
                break;                
        }

        if (entered_or_left_value === "1") {
            var entered_or_left_text = '入場';
        } 
        else {
            var entered_or_left_text = '退場'
        }

        document.getElementById("page-name").innerText = room_name_value + '/' + entered_or_left_text;

        

        // qrコードの処理
        var video = document.createElement("video");
        var canvasElement = document.getElementById("canvas");
        var canvas = canvasElement.getContext("2d");
        
        function drawLine(begin, end, color) {
	        canvas.beginPath();
	        canvas.moveTo(begin.x, begin.y);
	        canvas.lineTo(end.x, end.y);
	        canvas.lineWidth = 4;
	        canvas.strokeStyle = color;
	        canvas.stroke();
        }

        let cameraMode;// カメラを切り替えるための値

        function cameraChange(){
            const checkBox = document.getElementById('camera-checkbox');
            
            if (checkBox.checked == true) {
                cameraMode = 'user';
            }
            else {
                cameraMode = 'environment';
            }
            
            console.log(cameraMode);
        }

        navigator.mediaDevices.getUserMedia({ video: { facingMode: cameraMode } }).then(function(stream) {
	        video.srcObject = stream;
	        video.setAttribute("playsinline", true);
	        video.play();
	        requestAnimationFrame(tick);
        });

		//for test----------
		let quick_flag = new Boolean(true)
		$('input[name="check"]').change(function() {
			quicK_flag = $("#quick").prop("checked");
		})
		//------------------

		var prev_data = 0
        function tick() {
	        if (video.readyState === video.HAVE_ENOUGH_DATA) {
                canvasElement.height = video.videoHeight;
                canvasElement.width = video.videoWidth;
                canvas.drawImage(video, 0, 0, canvasElement.width, canvasElement.height);
                var imageData = canvas.getImageData(0, 0, canvasElement.width, canvasElement.height);
                var code = jsQR(imageData.data, imageData.width, imageData.height, {
	                inversionAttempts: "dontInvert",
                });
                if (code) {
	                drawLine(code.location.topLeftCorner, code.location.topRightCorner, "#FF3B58");
	                drawLine(code.location.topRightCorner, code.location.bottomRightCorner, "#FF3B58");
	                drawLine(code.location.bottomRightCorner, code.location.bottomLeftCorner, "#FF3B58");
	                drawLine(code.location.bottomLeftCorner, code.location.topLeftCorner, "#FF3B58");

                    console.log(code.data);
                    $('#id_user_num').val(code.data);

					if ((code.data != prev_data) && quick_flag) {
						validation();
					}

					prev_data = code.data
                    document.getElementById("outputMessage").innerText = "読み取り成功！";
                } else {
	                console.log("No QR code detected.");
                    document.getElementById("outputMessage").innerText = "QRコードをかざしてください。";
                }
	        }
            requestAnimationFrame(tick);
        }
    </script>
</body>
</html>